### ISSUE TITLE
pkgdown development mode

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/blueprints#100]
pkgdown offers 4 [development modes](https://pkgdown.r-lib.org/reference/build_site.html#development-mode): 

- `auto`
- `release`
- `devel`
- `unreleased`

At the moment, Epiverse-TRACE packages use either `auto`, or `release` (the default).

At the last development meeting, we discussed how `auto` could confuse users by providing two versions of the same site, possibly with conflicting information, or with information that doesn't match their installed version.
This lead us to call for a poll here to try and harmonize the use of these development mode across the project.

Here are the potential options we identified:

- keep `auto` but add visual elements (different colours, banner, etc.) to really insist on the difference between the release site and the development site
- use `dev` and always only offer the development site, with a prompt for users to update to the latest version if they detect mismatch with their existing version. Vignettes and documentation for their current version is still available locally via `help()` and `browseVignettes()`.
- use `unreleased` (only one website) until the package is on CRAN and then switch to `auto` (release + dev website). The rationale here is that we expect most users to install from CRAN and it would be good to direct them to the frozen release site, with an option to manually switch to the dev website if they installed from GitHub (which suggests they are probably more comfortable with R package lifecycle). This would also implement the first suggestion from this list.

**Comment by pratikunterwegs** [comment]
Thanks. I think option 3 reflects the most common user experience and would be the way to go. It would probably also help users to have a dev site URL in the Readme for sites using `auto`, similar to dev version installation instructions.

**Comment by sbfnk** [comment]
I agree on option (3) as preferred. For the link in the README, here's an example
https://github.com/epiforecasts/EpiNow2/blob/5c5a7266e0033445e5142e7a164ffd0df3b1cbeb/README.Rmd#L118

**Comment by joshwlambert** [comment]
I also prefer option 3.

**Comment by joshwlambert** [comment]
Can we write this up in the blueprints and close this issue as we've reached a consensus?
