### ISSUE TITLE
suggestion: use lightbox for the principles picture

### ISSUE THREAD

**Issue by maelle** [epiverse-trace/blueprints#105]
**Is your feature request related to a problem? Please describe.**

When reading the principles chapter I wanted to make the diagram bigger.

**Describe the solution you'd like**

Maybe it'd make sense to use https://quarto.org/docs/output-formats/html-lightbox-figures.html#galleries

**Additional context**

I opened the image in another browser window.

**Comment by Bisaloo** [comment]
Yes, I like this suggestion!

Would you be able to open a PR for it please? :smiley:
