### ISSUE TITLE
Documentation of decisions made around each discussion

### ISSUE THREAD

**Issue by jpavlich** [epiverse-trace/blueprints#17]
What are the plans to document the results of each discussion in the `issues` section?

Since some of those discussions directly affect development, it would be nice to have a structured document that explains the adopted policies. Is this going to be part of the blueprints document? Should it be a separate one?

**Comment by thibautjombart** [comment]
Absolutely! The current plan is to expand the current blueprints into a book, where the first chapter is the current blueprints, giving an overall view of core principles, and then individual chapters will document decisions and provide guidelines/examples on how to implement them. Does it make sense?
