### ISSUE TITLE
Correct contributing guide bullet 5

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/blueprints#40]
The contribution guide point 5 says to edit `index.qmd` but I think it should be `principles.qmd`.

**Comment by Bisaloo** [comment]
I believe it should be something like "the relevant `.qmd` file". This is a remnant of the time when we add a single page.

**Comment by jamesmbaazam** [comment]
Agreed. I noticed that after I opened the issue. I will submit a quick PR.
