### ISSUE TITLE
Consider contrasting colors in the mindmap

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/blueprints#56]
I find it hard to read the text on the [mindmap](https://github.com/epiverse-trace/blueprints/blob/215f2c09459d919f4b66478e36271a584a999d21/figures/mindmap.svg) mainly because it uses light blue on a white background. In a well-lit room, this can be hard to read in a presentation slide, for example. Could you consider improving the contrast in the image by using darker colors for the text, for example?

**Comment by Bisaloo** [comment]
Here is an alternative option

![mindmap_contrast](https://github.com/epiverse-trace/blueprints/assets/10783929/f3c4525e-b4b7-4ffa-8f38-f581ae208b2d)

**Comment by jamesmbaazam** [comment]
Ah, much better. Might be good to get feedback from others.
