### ISSUE TITLE
Provide deeper hierarchy on side bar

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/blueprints#60]
It would be easier to navigate the blueprints website if the left sidebar provided a deeper hierarchy. I notice that the table of contents on the right nav bar expands when a page is opened, but I would find it easier if it was all on the left side.

**Comment by chartgerink** [comment]
Appreciate the feedback @jamesmbaazam - given that we cannot fulfill all needs and this has not been topic of wider discussion, I am closing this issue as there is an existing Table of contents on each page.

**Comment by jamesmbaazam** [comment]
I'm not sure others were aware of this issue (to be discussed) but it's fine to close it as it was a personal preference.
