### ISSUE TITLE
Change repo member rights to edit comments by others

### ISSUE THREAD

**Issue by jamesmbaazam** [epiverse-trace/blueprints#69]
I just noticed that any member of this repo can edit a comment written by another. I think this is potentially problematic and should be changed.

**Comment by Bisaloo** [comment]
This is a GitHub feature we have no control on: https://docs.github.com/en/communities/moderating-comments-and-conversations/managing-disruptive-comments#editing-a-comment

**Comment by jamesmbaazam** [comment]
Oh, interesting. I guess it's good that we can see the edit history.
