### ISSUE TITLE
add chuck to make the two steps in Partial Review more visible to reader

### ISSUE THREAD

**Issue by avallecam** [epiverse-trace/blueprints#89]
The code chunks make steps more visible. The two steps in [Full review](https://epiverse-trace.github.io/blueprints/code-review.html#full-package-review) are visible. However, in the Partial review, we only have one chunk.

In the line below, we have two steps, one within the paragraph and the second in a code chunk

https://github.com/epiverse-trace/blueprints/blob/9c74b345c5b2be8ba3c224a4e60e61dbca46913a/code-review.qmd#L40-L47

We can split this paragraph, and compare with [current output](https://epiverse-trace.github.io/blueprints/code-review.html#partial-review), It can look like this:

---

A second use of partial code review is reviewing the changes between version releases. More generally, this can be considered as reviewing changes between a chosen branch and an arbitrary commit in the past, but for the purpose of this example we will focus on differences between versions. For this mock example, lets say a new version (v0.3.0) of a package is ready to be released and all the differences to the previously release version (v0.2.0) need to be reviewed. A branch, which we will call `v_020`, is created from the commit that is tagged with the v0.2.0 release. To find this commit we can run `git show-ref --tags`. This should return each commit SHA with it's associated release tag. Then create a new branch from this commit using `git branch v_020 <commit_sha>` (replacing `<commit_sha>` with the chosen commit from the previous command). Push this branch with `git push origin v_020`. 

```sh
git show-ref --tags
git branch v_020 <commit_sha>
git push origin v_020
```

We then want to create a branch from our stable branch (e.g. `main`) for the purpose of the review, here we will call it `review`.

```sh
git branch review
git push origin review
```

The pull request can now be made from the `review` branch to the `v_020` branch and will provide the difference between versions.

----

**Comment by Bisaloo** [comment]
Thanks for the report, it makes sense. I also like having code instead of just a textual description. Could you open a PR with these changes please?
