### ISSUE TITLE
Add ORCID policy?

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/blueprints#97]
We have an implied policy throughout the packages to provide thorough credits to contributors. This includes their role, but we also include [ORCIDs](https://orcid.org) where possible.

The blueprints do not state any recommendations on ORCID use. Do we want to explicitly recommend the use of ORCIDs throughout the Epiverse packages? This would help assign proper credit and disambiguate authors in the long run.

See also https://epiverse-trace.github.io/blueprints/contribution-acknowledgements.html

**Comment by Bisaloo** [comment]
Sure, sounds good. Let's make it explicit.
